version: "3"
services:
  script:
    build: .
    network_mode: host
    environment:
      # Required
      ZONE_ID: XXX
      DOMAINS: example.com,foo.example.com,baa.example.com
      API_TOKEN: XXX

      # Optional
      IPV6: "true" # (default = false)
      # IPV4: "false" # (default = false)
      # TTL: "1" # must be inbetween 60-86400; 1 = automatic (default = 1)
      # CRON: "*/10 * * * *" # every 10 minutes (default)
      # LOG_LEVEL: "INFO" # (default; info, debug)
